import Head from 'next/head';
import Image from 'next/image';
import Gallery from '../components/gallery/gallery.js';
import styles from '../styles/Home.module.css';
import React from 'react';




export default function Home() {
 


  const [music, setMusic] = React.useState("");
  const [genres, setGenres] = React.useState("");

  React.useEffect(() => {

    const fetchMusic = async () => {

      const response = await fetch('/api/hello');

      const  music  = await response.json();
      // console.log(music.feed.results);
      setMusic(music.feed.results);

      setGenres(music.feed.results.reduce((genresToAdd, album) => {
        const genres = album.genres || [];
        genres.forEach((genre) => {
          genresToAdd[genre.name] = genresToAdd[genre.name] || [];
          genresToAdd[genre.name].push(album);
        })
        // genresToAdd[album.genre] = genres[album.genre] || [];
        // genresToAdd[album.genre].push(album);
        return genresToAdd;
      }, {}));

    };

    fetchMusic();

  }, []);

   // // const music = fetch('/api/hello').then((m)=>m.json()).then((list)=>list.feed.results);
  //  const genres = this.state.music.then((music) => {
  //   console.log(music);
  //   return music.reduce((genres, album) => {
  //     genres[album.genre] = genres[album.genre] || [];
  //     genres[album.genre].push(album);
  //     return genres;
  //   })
  // });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Gallery genres={genres} music={music}></Gallery>
        {/* {props.genres.map((album) => {

        })} */}
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
