import Head from 'next/head';
import Image from 'next/image';
import Gallery from '../components/gallery/gallery.js';
import styles from '../styles/Home.module.css';
import React from 'react';



let loading = false;

export default function Home() {
 
  

  const [music, setMusic] = React.useState("");


    const fetchMusic = async () => {

      const response = await fetch('/api/hello');

      const  music  = await response.json();

      loading = false;
      setMusic(music.feed.results);

    };


    if (music.length === 0 && !loading) {
      loading = true;
      fetchMusic();
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>FilmHub Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Gallery music={music}></Gallery>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
